engines:
  rubocop:
    enabled: true
  golint:
    enabled: true
  eslint:
    enabled: true
  scss-lint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
        - javascript
ratings:
  paths:
  - "**.js"
  - "**.json"
  - "**.pug"
  - "**.sass"
exclude_paths:
- node_modules/**
- test/**